version: "3.9"

services:
  chatbot:
    build: .
    container_name: anti-phishing-chatbot
    restart: always
    ports:
      - "7860:7860"
    environment:
      - APP_ENV=production
      - GRADIO_SERVER_PORT=7860
      - GRADIO_SERVER_NAME=0.0.0.0
    volumes:
      - ./app:/app/app              # hot-reload app code. allows code edits without rebuilding the container
      - ./knowledge_base:/app/knowledge_base
    command: uvicorn app.main:app --host 0.0.0.0 --port 7860 --reload
    # use reload for local development; have to remove for production deployments
